spring:
  datasource:
    name: piradio
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./database/piradio
    username: pi
    password: pi
  jpa:
    database-platform: H2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: update
    show-sql: true
  # defer-datasource-initialization: false
  flyway:
    locations: classpath:db/migration/
    baselineOnMigrate: true
    schemas: PUBLIC
    enabled: true

server:
  port: 8000

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
      port: 8001
    database:
      skip-create: false
      migration.username: pi
      migration.password: pi

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    path: "/swagger-ui.html"
  show-actuator: true
  group-configs:
    - group: piradio
      paths-to-match: /**
