## Hibernate Properties
# Hibernate ddl auto (create, create-drop, validate, update)
spring:
  datasource:
    name: piradio
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./database/piradio
    username: pi
    password: pi
  jpa:
    database-platform: H2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
    show-sql: true
  # defer-datasource-initialization: false
  ## QuartzProperties
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
  flyway:
    locations: classpath:db/migration/
    baselineOnMigrate: true
    schemas: PUBLIC
    enabled: true

server:
  port: 8000

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    - group: piradio
      paths-to-match: /**

piradio:
  volume: 80